import fatass
from fatass.topology.cv.materials import Materials as Materials
from fatass.topology.cv.preferences import Preferences as Preferences


def build(materials: Materials, preferences: Preferences):
    fatass.free(
        silent=True,
        model="opus",
        tools="Read,Write,Edit,Glob,Grep,Bash",  # Bash: the materials subdirectories hold PDFs, else Read misreads them as password-protected
        readable=[materials, preferences],
        prompt=(
            f"Read `preferences.json` in the readable directory for this "
            f"node's `preferences` dependency: the candidate's answers to "
            f"the CV-writing questionnaire — which sections they want and "
            f"in what order, the citation style for publications, whether "
            f"to bold their own name in co-authored entries, whether to "
            f"split publications by subtype, and the CV's field, purpose, "
            f"and intended scope. That file only exists once the candidate "
            f"has filled out the questionnaire app: if it isn't there, do "
            f"nothing and write nothing.\n\n"
            f"Also read every file under every subdirectory of the readable "
            f"directory for this node's `materials` dependency, including "
            f"its sub nodes: `education/`, `positions/`, "
            f"`publications_and_presentations/`, `funding_and_honors/`, "
            f"`teaching_and_service/`, `personal_projects/`, and "
            f"`references/`. Each holds the raw facts for its own category. "
            f"Any of them may be empty. A subdirectory may contain PDFs, "
            f"and may hold a `from_current_cv.md` written by that subnode's "
            f"own extraction transform alongside anything the candidate "
            f"added by hand — read all of it, both sources count equally. "
            f"Three of these bundle two distinct fact categories under "
            f"their own \"## \" subheadings: "
            f"`publications_and_presentations/` (publications; "
            f"presentations and invited talks), `funding_and_honors/` "
            f"(grants and funding; awards and honors), and "
            f"`teaching_and_service/` (teaching; service).\n\n"
            f"Assemble the academic CV as `cv.md` in the current "
            f"directory.\n\n"
            f"Include exactly the sections requested in preferences.json, "
            f"in the requested order — no section it doesn't ask for, none "
            f"of the ones it does left out, and no reordering. Draw each "
            f"section from its corresponding materials subdirectory:\n\n"
            f"- Education — `education/`\n"
            f"- Positions/Appointments — `positions/`\n"
            f"- Publications — `publications_and_presentations/`, its "
            f"publications facts\n"
            f"- Presentations and Invited Talks — "
            f"`publications_and_presentations/`, its presentations facts\n"
            f"- Grants and Funding — `funding_and_honors/`, its grants "
            f"facts\n"
            f"- Awards and Honors — `funding_and_honors/`, its awards "
            f"facts\n"
            f"- Teaching — `teaching_and_service/`, its teaching facts\n"
            f"- Service — `teaching_and_service/`, its service facts\n"
            f"- Personal Projects — `personal_projects/`\n"
            f"- References — `references/`\n\n"
            f"Publications and Presentations are always two separate CV "
            f"sections when both are requested, even though their source "
            f"facts share the one `publications_and_presentations/` folder; "
            f"the same holds for Grants and Awards out of "
            f"`funding_and_honors/`, and for Teaching and Service out of "
            f"`teaching_and_service/`.\n\n"
            f"Populate every section only from facts actually present in "
            f"its corresponding materials subdirectory. Never invent a "
            f"degree, position, publication, grant, award, teaching role, "
            f"service role, presentation, personal project, or referee that "
            f"is not backed by a specific file under `materials` — every "
            f"entry in the CV must trace back to something you actually "
            f"read. Do not embellish an entry with a detail (a date, a "
            f"venue, a title, a funding amount, a co-author) that its "
            f"source doesn't state.\n\n"
            f"Within each section, order entries reverse-chronologically, "
            f"most recent first — the standard academic CV convention — "
            f"unless the section is inherently unordered (References, for "
            f"instance).\n\n"
            f"Format the publications section in the citation style "
            f"preferences.json requests, applied consistently to every "
            f"entry. If it asks for the candidate's own name to be bolded, "
            f"bold it in every co-authored entry. If it asks for "
            f"publications to be split by subtype (journal articles, "
            f"conference papers, book chapters, preprints/working papers), "
            f"split them into those subsections; otherwise list them as one "
            f"combined section. Honor the other stated preferences too — "
            f"the requested scope and any page-count cap, and whether an "
            f"\"in preparation\"/\"under review\" subsection is wanted.\n\n"
            f"If a requested section has no corresponding material — the "
            f"subdirectory is empty, or holds nothing for that section's "
            f"half of it — still include the section heading, with a brief "
            f"\"None to date\" placeholder underneath. Never omit a "
            f"requested section, and never fill one with invented content "
            f"to avoid the placeholder.\n\n"
            f"Then write `log.md` in the current directory, recording: "
            f"which materials files you read, listed by path; and which "
            f"requested sections had no material to draw on and so got the "
            f"placeholder."
        ),
    )
