#!/bin/sh
# Fleshes out every transform stub scaffolded by phd_application/layout.sh
# with real logic, via `modify <transform>@<node.path> --prompt ...` (and,
# for the one node with no Node-typed dependency, `modify build@profile.
# questionnaire`). Run layout.sh first — modify requires the transform file
# to already exist.
#
# Every line below is a real, billable Claude CLI call (fatass modify always
# invokes the agent) — review before running, and run deliberately rather
# than all at once if you want to check intermediate output.
#
# Assumes the shell's cwd is the repo root and FATASS_NODE is already set to
# the project entry node (`phd_application`) — every node.path below is
# written relative to it, with no leading `phd_application.`.
#
# Safety note: outreach.dispatch is written to default to a dry run and to
# require an explicit --live flag plus typed confirmation before it will
# actually send mail, and to only ever send what outreach.review has marked
# approved. Don't loosen that without meaning to.

# --- profile: the survey app the applicant fills out by hand ---------------
python -m fatass modify build@profile.questionnaire --prompt 'Define build() with no parameters. Generate two files in the current directory: `app.py` and `index.html`, for a small local web app that lets the applicant fill out a PhD-application scouting profile. `app.py` is the server: a minimal, dependency-light HTTP server (standard library only, e.g. `http.server`) that serves `index.html`, exposes an endpoint for the page to read the current profile state, and an endpoint the page submits to. On startup and on each read request, the server reads existing state from `../preferences.json` (one directory up from `app.py`), if present, so the page shows the current values. On submit, the server writes the resulting profile to `../preferences.json`. `index.html` is a stylized, multipage survey (plain HTML/CSS/JS, no build step, no external dependencies) with pagination and a final review page before submitting. Cover these fields, grouped into sensible pages: target research areas/subfields and keywords; preferred degree start term; geographic/country preferences and any visa or citizenship constraints; funding requirements (fully funded only, vs. assistantship/fellowship acceptable); target institution tiers/prestige tolerance; preferred advisor seniority or lab size (junior PI vs. established lab); remote vs. onsite fit; the application deadline window to prioritize; the maximum number of programs/professors to target; desired tone/formality for outreach emails; and a free-text box for professors, labs, or institutions already known to the applicant so they are not treated as new candidates later. Style: calm, academic visual theme, applied consistently across every page.'

# --- hunt: cast a wide net, enrich each hit, then rank -- the emphasis here -
python -m fatass modify build@hunt.landscape --prompt 'Define build(profile: Profile), where profile depends on node `profile` (the parent node whose nodes/ directory holds preferences.json once the applicant has filled out the questionnaire app). Read preferences.json under the dependency readable directory. Search the open web (university/department directories, faculty listing pages, lab pages, Google Scholar, DBLP, OpenReview, arXiv author pages, and PhD-position aggregator sites) for graduate programs, labs, and individual professors whose research plausibly matches the target research areas and keywords in preferences.json, respecting its stated geographic, funding, and timeline constraints. Cast a wide net — this stage is a longlist, not a shortlist — and skip anything the applicant already listed as known in preferences.json. For each candidate found, capture: institution, department/program, professor name(s) if identifiable, program or faculty page URL, the specific fit signal that surfaced it, and any funding/admission notes visible on the page. Write the result as `landscape.json` (a JSON array of candidate objects) and `log.md` (the search queries run, sources checked, and candidate count found) in the current directory.'

python -m fatass modify build@hunt.profiles --prompt 'Define build(landscape: Landscape, profile: Profile), where landscape depends on node `hunt.landscape` and profile depends on node `profile`. Read landscape.json under the landscape dependency readable directory and preferences.json under the profile dependency readable directory. For every candidate in landscape.json, fetch their faculty/lab page and recent publication listing (their lab site, Google Scholar, DBLP, or arXiv author page) and build an enriched profile: their research directions over roughly the last three years, two or three notable recent papers with titles, any visible "accepting students" or lab-openness signal, funding status if stated, application deadline if stated, and a short note on fit against preferences.json citing specific evidence just gathered. If a candidate page cannot be found or fetched, keep the candidate with a `status: "unreachable"` entry and a one-line reason rather than dropping it silently. Write the result as `profiles.json` (one enriched object per candidate, keyed by the same identity used in landscape.json) and `log.md` in the current directory.'

python -m fatass modify build@hunt.shortlist --prompt 'Define build(profiles: Profiles, profile: Profile), where profiles depends on node `hunt.profiles` and profile depends on node `profile`. Read profiles.json and preferences.json under the respective dependency readable directories. Score every non-"unreachable" candidate 1-5 on probable fit and likelihood of a successful application, weighing research fit, funding availability, deadline feasibility, institution-tier tolerance, and geography exactly as preferences.json states them, and write one rationale paragraph per candidate citing specific facts from profiles.json. Exclude candidates with a hard disqualifier (no funding when fully-funded is required, deadline already passed, explicitly not accepting students) into a separate `excluded` list with the reason, rather than scoring them. Rank the surviving candidates by score descending, capped at the maximum program count from preferences.json (default top 20 if unset). Write the result as `shortlist.json` (the ranked array — rank, candidate identity, score, rationale, and the specific facts to reference in outreach — plus the `excluded` list) and a human-readable `shortlist.md`, and `log.md`, in the current directory.'

# --- outreach: personalized emails, a human gate, then a safe, gated send --
python -m fatass modify build@outreach.emails --prompt 'Define build(shortlist: Shortlist, profile: Profile, documents: Documents), where shortlist depends on node `hunt.shortlist`, profile depends on node `profile` (preferences.json, for the requested tone/formality), and documents depends on node `profile.documents` (its readable directory has one subdirectory per material — cv, transcripts, publications, writing_sample, references — populated by hand by the applicant; any of these may be empty). Read shortlist.json, preferences.json, and every file present under each documents subdirectory. For every candidate in shortlist.json, compose one personalized outreach email: a specific, non-generic subject and body that references the professor real recent work (from shortlist.json rationale/facts) and draws one or two concrete, real details from the applicant own cv/publications/writing_sample to state genuine fit. Never invent the applicant credentials or the professor work, and never invent content for a missing document — write around the gap instead. Match tone/formality to preferences.json. Write one file per candidate as `emails/<slug>.md` (recipient name/email if known, subject, body) plus a manifest `emails/index.json` listing every generated email (slug, recipient, institution, and which document kinds should be attached), and `log.md` in the current directory. Do not send anything — this transform only drafts.'

python -m fatass modify build@outreach.dispatch --prompt 'Define build(emails: Emails, review: Review), where emails depends on node `outreach.emails` and review depends on node `outreach.review` (a manual gate directory the applicant populates by hand with an `approved.json` listing the slugs, from emails/index.json, that are cleared to send — treat a missing or empty approved.json as "nothing approved yet", not an error). Read emails/index.json and every emails/<slug>.md file under the emails dependency readable directory, and approved.json under the review dependency readable directory. If `send_config.example.json` does not already exist in the current directory, write one: placeholder SMTP or Gmail-API settings, a sender name/email placeholder, and a `delay_seconds_between_sends` rate-limit setting — never fabricate or fill in real credentials. Write `send_queue.json`: one entry per approved slug only (recipient, subject, body file path, attachments to include from profile.documents, `sent: false`); slugs not present in approved.json must not appear here. Write `send.py`: a standalone stdlib-only script (`smtplib`/`email`) that reads real settings from a sibling `send_config.json` (not the `.example.json`) and iterates send_queue.json; it must default to a `--dry-run` mode that only prints what each send would do, require both an explicit `--live` flag and a typed "SEND" confirmation before it will actually send mail, honor the configured delay between sends, and mark each entry `sent: true` with a timestamp as it goes so a rerun never re-sends an already-sent entry. Write `log.md` stating how many emails were approved, queued, and skipped (and why) in the current directory.'
