#!/bin/sh
# Fleshes out every transform stub scaffolded by cv/layout.sh with real
# logic, via `modify <transform>@<node.path> --prompt ...`. Run layout.sh
# first — modify requires the transform file to already exist.
#
# Every line below is a real, billable Claude CLI call (fatass modify
# always invokes the agent) — review before running, and run deliberately
# rather than all at once if you want to check intermediate output.
#
# Assumes the shell's cwd is the repo root. Every node.path below is
# absolute (`~.cv....`), so this runs correctly regardless of whatever
# FATASS_NODE currently is — no `cd` needed first.
#
# --model/--tools/--silent are set deliberately per transform, not left on
# fatass's defaults:
#   - cv.preferences: sonnet, no PDF/network tools — it only scaffolds a
#     generic local survey app, never reads the candidate's own materials.
#   - cv.materials.*'s extraction transforms: sonnet plus Bash — parsing
#     current_cv (plausibly a PDF, which the Read tool alone can misread
#     as password-protected) into one or two categories is a bounded
#     extraction task, not the kind of open-ended judgment call that needs
#     opus.
#   - cv.draft and cv.audit: opus (the actual CV content — and catching a
#     fabricated or inconsistent entry in it — is the whole point of this
#     pipeline) plus Bash, since materials/* may itself contain PDFs
#     (diploma scans, award certificates, publication preprints) besides
#     whatever came from current_cv.
# Every transform stays --silent (unattended, batch-pipeline convention)
# — unlike phd_application.outreach.dispatch, nothing here sends anything
# anywhere; the candidate reviews cv.md themselves afterward.

# --- current_cv: extraction transforms, one per materials folder --------
# All seven share one shape: build(current_cv: CurrentCv), where
# current_cv depends on node `cv.current_cv` (may be empty — a candidate
# writing their first academic CV has nothing to extract from, in which
# case the transform does nothing). Each writes only `from_current_cv.md`
# in its own directory, alongside — never over — anything the candidate
# has already added there by hand. Three folders bundle two fact
# categories each; their prompts keep the two clearly subheaded within
# the one file so cv.draft can still render them as separate CV sections.

python -m fatass modify build@~.cv.materials.education --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(current_cv: CurrentCv), where current_cv depends on node `cv.current_cv` (the candidate'"'"'s existing CV file, if any — its readable directory may be empty for a candidate writing their first academic CV, in which case do nothing and write nothing). Read current_cv'"'"'s readable directory. Extract every degree earned, institution, advisor, dissertation/thesis title, and date mentioned in it — never infer or add a detail the CV doesn'"'"'t state. Write the extracted entries to `from_current_cv.md` in the current directory, one entry per degree. Do not touch or overwrite any other file already in the current directory — the candidate may have added entries here by hand, and both sources are meant to coexist. If current_cv has no education section, do not create `from_current_cv.md` at all.'

python -m fatass modify build@~.cv.materials.positions --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(current_cv: CurrentCv), where current_cv depends on node `cv.current_cv` (the candidate'"'"'s existing CV file, if any — its readable directory may be empty for a candidate writing their first academic CV, in which case do nothing and write nothing). Read current_cv'"'"'s readable directory. Extract every academic appointment and employment entry (postdoctoral positions, faculty roles, visiting positions), with institution, title, and dates — never infer or add a detail the CV doesn'"'"'t state. Write the extracted entries to `from_current_cv.md` in the current directory, one entry per position. Do not touch or overwrite any other file already in the current directory — the candidate may have added entries here by hand, and both sources are meant to coexist. If current_cv has no positions section, do not create `from_current_cv.md` at all.'

python -m fatass modify build@~.cv.materials.publications_and_presentations --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(current_cv: CurrentCv), where current_cv depends on node `cv.current_cv` (the candidate'"'"'s existing CV file, if any — its readable directory may be empty for a candidate writing their first academic CV, in which case do nothing and write nothing). Read current_cv'"'"'s readable directory. Extract two kinds of entry, under two clearly separate subheadings in one output file: (1) every publication (journal article, conference paper, book chapter, or preprint) with its full citation details (authors, title, venue, year) exactly as stated, and (2) every invited talk and conference presentation with venue and date. Never infer or add a detail the CV doesn'"'"'t state. Write the result to `from_current_cv.md` in the current directory as two sections, "## Publications" and "## Presentations", each with one entry per item — omit either subheading entirely if current_cv has nothing for it. Do not touch or overwrite any other file already in the current directory — the candidate may have added entries here by hand, and both sources are meant to coexist. If current_cv has neither section, do not create `from_current_cv.md` at all.'

python -m fatass modify build@~.cv.materials.funding_and_honors --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(current_cv: CurrentCv), where current_cv depends on node `cv.current_cv` (the candidate'"'"'s existing CV file, if any — its readable directory may be empty for a candidate writing their first academic CV, in which case do nothing and write nothing). Read current_cv'"'"'s readable directory. Extract two kinds of entry, under two clearly separate subheadings in one output file: (1) every grant or funding award, with the funding body, the candidate'"'"'s role (PI, co-PI, etc.), and dates, and (2) every honor, award, and fellowship, with the awarding body and date. Never infer or add a detail the CV doesn'"'"'t state. Write the result to `from_current_cv.md` in the current directory as two sections, "## Grants and Funding" and "## Awards and Honors", each with one entry per item — omit either subheading entirely if current_cv has nothing for it. Do not touch or overwrite any other file already in the current directory — the candidate may have added entries here by hand, and both sources are meant to coexist. If current_cv has neither section, do not create `from_current_cv.md` at all.'

python -m fatass modify build@~.cv.materials.teaching_and_service --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(current_cv: CurrentCv), where current_cv depends on node `cv.current_cv` (the candidate'"'"'s existing CV file, if any — its readable directory may be empty for a candidate writing their first academic CV, in which case do nothing and write nothing). Read current_cv'"'"'s readable directory. Extract two kinds of entry, under two clearly separate subheadings in one output file: (1) every course taught, with institution, the candidate'"'"'s role (instructor, teaching assistant, etc.), and dates, and (2) every committee role, peer-reviewing role, editorial role, and other professional service entry, with dates. Never infer or add a detail the CV doesn'"'"'t state. Write the result to `from_current_cv.md` in the current directory as two sections, "## Teaching" and "## Service", each with one entry per item — omit either subheading entirely if current_cv has nothing for it. Do not touch or overwrite any other file already in the current directory — the candidate may have added entries here by hand, and both sources are meant to coexist. If current_cv has neither section, do not create `from_current_cv.md` at all.'

python -m fatass modify build@~.cv.materials.personal_projects --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(current_cv: CurrentCv), where current_cv depends on node `cv.current_cv` (the candidate'"'"'s existing CV file, if any — its readable directory may be empty for a candidate writing their first academic CV, in which case do nothing and write nothing). Read current_cv'"'"'s readable directory. Extract every independent or personal project, open-source contribution, and side project not tied to a formal position or already-listed publication, with dates and a brief description — never infer or add a detail the CV doesn'"'"'t state. Write the extracted entries to `from_current_cv.md` in the current directory, one entry per project. Do not touch or overwrite any other file already in the current directory — the candidate may have added entries here by hand, and both sources are meant to coexist. If current_cv has no such section, do not create `from_current_cv.md` at all.'

python -m fatass modify build@~.cv.materials.references --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(current_cv: CurrentCv), where current_cv depends on node `cv.current_cv` (the candidate'"'"'s existing CV file, if any — its readable directory may be empty for a candidate writing their first academic CV, in which case do nothing and write nothing). Read current_cv'"'"'s readable directory. Extract any referee explicitly listed (name, affiliation, contact) — many CVs simply say "available upon request" instead of listing referees, in which case there is nothing to extract. Never infer or add a detail the CV doesn'"'"'t state. Write the extracted entries to `from_current_cv.md` in the current directory, one entry per referee. Do not touch or overwrite any other file already in the current directory — the candidate may have added entries here by hand, and both sources are meant to coexist. If current_cv lists no referees, do not create `from_current_cv.md` at all.'

# --- preferences: the survey app the candidate fills out by hand --------
# Note: the questionnaire still offers Publications, Presentations,
# Grants, Awards, Teaching, and Service as separate selectable CV
# sections, even though their raw materials now share a folder — the
# materials-folder merge above is purely about where the input facts
# live, not about how the rendered CV is structured.
python -m fatass modify build@~.cv.preferences --silent --model sonnet --tools "Read,Write,Edit,Glob,Grep" --prompt 'Define build() with no parameters. Generate two files in the current directory: `app.py` and `index.html`, for a small local web app that lets an academic fill out their CV-writing preferences. `app.py` is the server: a minimal, dependency-light HTTP server (standard library only, e.g. `http.server`) that serves `index.html`, exposes an endpoint for the page to read the current preferences state, and an endpoint the page submits to. On startup and on each read request, the server reads existing state from `../preferences.json` (one directory up from `app.py`), if present, so the page shows the current values. On submit, the server writes the resulting preferences to `../preferences.json`. `index.html` is a stylized, multipage survey (plain HTML/CSS/JS, no build step, no external dependencies) with pagination and a final review page before submitting. Cover these fields: target field/discipline; the CV'"'"'s purpose (tenure-track job market application, postdoc application, grant/fellowship application, tenure/promotion case, or general/all-purpose); desired scope (a comprehensive CV with no length limit, vs. a condensed biosketch-style CV capped at a stated page count); citation style for the publications list (e.g. APA, MLA, IEEE, or a field-specific numbered style) and whether to bold the candidate'"'"'s own name in co-authored entries; which sections to include and in what order, from: Education, Positions/Appointments, Publications, Presentations and Invited Talks, Grants and Funding, Awards and Honors, Teaching, Service, Personal Projects, References; whether to split publications into subtypes (journal articles, conference papers, book chapters, preprints/working papers) or list them in one combined section; and whether an "in preparation"/"under review" subsection should be included for publications not yet accepted. Style: a calm, professional/academic visual theme, applied consistently across every page.'

# --- draft: assemble the CV from materials + preferences -----------------
python -m fatass modify build@~.cv.draft --silent --model opus --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(materials: Materials, preferences: Preferences), where materials depends on node `cv.materials` (its readable directory has one subdirectory per materials category — education, positions, publications_and_presentations, funding_and_honors, teaching_and_service, personal_projects, references — any of which may be empty, may contain PDFs, and may hold a `from_current_cv.md` written by that subnode'"'"'s own extraction transform alongside anything the candidate added by hand; publications_and_presentations, funding_and_honors, and teaching_and_service each bundle two distinct fact categories under their own "## " subheadings) and preferences depends on node `cv.preferences` (preferences.json, once the candidate has filled out the questionnaire app). Read preferences.json and every file under each materials subdirectory. Assemble the academic CV as `cv.md` in the current directory: include exactly the sections requested in preferences.json, in the requested order — Publications and Presentations are always two separate CV sections if requested, even though their source facts share the publications_and_presentations folder; likewise Grants/Awards come from funding_and_honors, and Teaching/Service come from teaching_and_service. Populate every section only from facts actually present in its corresponding materials subdirectory — never invent a degree, position, publication, grant, award, teaching role, service role, presentation, personal project, or referee that is not backed by a specific file under materials. Within each section, order entries reverse-chronologically (most recent first), the standard academic CV convention, unless the section is inherently unordered. Format the publications section in the requested citation style, bolding the candidate'"'"'s own name in every co-authored entry if requested, and splitting by publication subtype if requested. If a requested section has no corresponding material, include the section heading with a brief "None to date" placeholder rather than omitting the section or fabricating content. Write `log.md` in the current directory: which materials files were read, and which requested sections had no material to draw on.'

# --- audit: fact-check against materials, fix formatting/consistency -----
python -m fatass modify build@~.cv.audit --silent --model opus --tools "Read,Write,Edit,Glob,Grep,Bash" --prompt 'Define build(draft: Draft, materials: Materials, preferences: Preferences), where draft depends on node `cv.draft` (cv.md), materials depends on node `cv.materials` (its readable directory has one subdirectory per materials category, with publications_and_presentations, funding_and_honors, and teaching_and_service each bundling two distinct fact categories under their own "## " subheadings), and preferences depends on node `cv.preferences`. Read cv.md, preferences.json, and every file under each materials subdirectory. Fact-check cv.md line by line against materials: flag and fix any degree, position, publication, grant, award, teaching role, service role, presentation, personal project, or referee entry that is not backed by a specific file under materials, and any date, title, or affiliation that does not match its source file exactly. Check formatting and internal consistency: the citation style is applied uniformly across every publication entry, sections appear in the order preferences.json requests, entries within each section are reverse-chronological, and the candidate'"'"'s own name is bolded consistently if requested. If preferences.json requests a condensed/page-limited CV, tighten the wording and trim the least-relevant entries (judged against the stated target field and CV purpose) rather than removing whole sections outright. Edit `cv.md` directly to fix anything found — preserve accurate content exactly, and change only what is actually wrong or inconsistent. Write `audit_log.md` in the current directory: every fact-check or formatting issue found and how it was fixed, or "no issues found" per section.'
