#!/bin/sh
# Fleshes out every transform stub scaffolded by thesis/layout.sh with real
# logic, via `modify <transform>@<node.path> --prompt ...`. Run layout.sh
# first — modify requires the transform file to already exist.
#
# Every line below is a real, billable Claude CLI call (fatass modify always
# invokes the agent) — review before running, and run deliberately rather
# than all at once if you want to check intermediate output.
#
# Assumes the shell's cwd is the repo root and FATASS_NODE is already set to
# the project entry node (`idea`) — every node.path below is written relative
# to it, with no leading `idea.`.

# --- review: literature synthesis and gap analysis --------------------------
python -m fatass modify build@review.synthesis --prompt 'Define build(corpus: Corpus, notes: Notes), where corpus depends on node `materials.literature.corpus` (the collected candidate papers on the LLM subfield) and notes depends on node `materials.literature.notes` (the student own reading notes on that corpus). Read every file under each dependency readable directory. For each paper, write a synthesis entry: its claim, method, and result, plus how the student notes qualify, question, or extend it. Group the entries into a taxonomy of the LLM subfield the thesis sits in (competing approaches, open disagreements, shared assumptions). Write the result as `synthesis.md` in the current directory. Also write `log.md`: the papers read and a summary of the taxonomy produced.'

python -m fatass modify build@review.gap --prompt 'Define build(synthesis: Synthesis, proposal: Proposal), where synthesis depends on node `review.synthesis` (the literature taxonomy) and proposal depends on node `materials.proposal` (the thesis proposal and advisor requirements). Read every file under each dependency readable directory. Identify the research gap: what the existing literature does not yet answer, where it disagrees, or where its methods do not transfer to the case the proposal describes. State the thesis novelty claim in one paragraph, then justify it against specific entries in synthesis.md. Write the result as `gap.md` in the current directory, and `log.md` summarizing what was read and the gap identified.'

python -m fatass modify build@review.related_work_plan --prompt 'Define build(synthesis: Synthesis, gap: Gap), where synthesis depends on node `review.synthesis` and gap depends on node `review.gap`. Read every file under each dependency readable directory. Plan the structure of the thesis Related Work chapter: which taxonomy groups from synthesis.md get their own section, in what order, and how each section sets up the gap identified in gap.md rather than just summarizing prior work. Write the result as `related_work_plan.md` (a section-by-section outline with, for each section, its argument and which synthesis entries it draws on) and `log.md` in the current directory.'

# --- design: turns the gap into a concrete, runnable research design -------
python -m fatass modify build@design.questions --prompt 'Define build(proposal: Proposal, gap: Gap), where proposal depends on node `materials.proposal` and gap depends on node `review.gap`. Read every file under each dependency readable directory. State the thesis formal research questions and, for each, a testable hypothesis about what an LLM experiment would need to show to answer it. Write the result as `questions.md` and `log.md` in the current directory.'

python -m fatass modify build@design.method --prompt 'Define build(questions: Questions, dataset: Dataset, synthesis: Synthesis), where questions depends on node `design.questions`, dataset depends on node `materials.dataset` (the raw dataset or benchmark available for experiments), and synthesis depends on node `review.synthesis` (for what methods and baselines prior work used). Read every file under each dependency readable directory. Design the experiment: which models and baselines are compared, independent and dependent variables, the metrics used to answer each research question, and which ablations would isolate which variable. Write the result as `method.md` and `log.md` in the current directory.'

python -m fatass modify build@design.protocol --prompt 'Define build(method: Method), where method depends on node `design.method`. Read every file under the dependency readable directory. Turn the experiment design into a fully specified protocol precise enough to implement without further judgment calls: exact model identifiers and versions, prompt templates, sampling parameters and seeds, dataset splits, the evaluation procedure and metric formulas, and the exact ablation configurations. Write the result as `protocol.md` and `log.md` in the current directory.'

# --- experiments: the empirical work -----------------------------------
python -m fatass modify build@experiments.harness --prompt 'Define build(protocol: Protocol), where protocol depends on node `design.protocol`. Read every file under the dependency readable directory. Implement the experiment harness as runnable code in the current directory: a script that calls the specified models against the specified dataset splits per the prompt templates and sampling parameters, and a script that computes the specified metrics from the resulting outputs. Also write `harness_notes.md` describing how to run each script and any assumption made where protocol.md underspecified something, and `log.md` summarizing what was implemented.'

python -m fatass modify build@experiments.pilot --prompt 'Define build(harness: Harness, protocol: Protocol), where harness depends on node `experiments.harness` and protocol depends on node `design.protocol`. Read every file under each dependency readable directory, then actually run the harness scripts on a small pilot subset (a handful of examples per condition). Record what ran, what failed, and any place the real output diverged from what protocol.md assumed. Write the result as `pilot_results.md` (raw pilot outputs plus issues found) and `protocol_fixes.md` (concrete fixes to apply before the main run, or "none needed"). Also write `log.md`.'

python -m fatass modify build@experiments.main_run --prompt 'Define build(harness: Harness, protocol: Protocol, pilot: Pilot), where harness depends on node `experiments.harness`, protocol depends on node `design.protocol`, and pilot depends on node `experiments.pilot`. Read every file under each dependency readable directory, applying any fixes noted in pilot/protocol_fixes.md. Run the harness across the full experiment matrix specified in protocol.md. Save the raw per-example outputs and computed metrics as data files (csv/json) in the current directory, plus `run_summary.md` describing what ran, run duration, and any anomalies. Also write `log.md`.'

python -m fatass modify build@experiments.ablations --prompt 'Define build(harness: Harness, main_run: MainRun, method: Method), where harness depends on node `experiments.harness`, main_run depends on node `experiments.main_run`, and method depends on node `design.method` (for which ablations were specified). Read every file under each dependency readable directory. Run each ablation configuration with the harness, comparing results against the corresponding main_run condition. Save the raw ablation outputs and metrics as data files in the current directory, plus `ablation_summary.md` stating, per ablation, what changed in the result and what that implies about the isolated variable. Also write `log.md`.'

python -m fatass modify build@experiments.analysis --prompt 'Define build(main_run: MainRun, ablations: Ablations, method: Method), where main_run depends on node `experiments.main_run`, ablations depends on node `experiments.ablations`, and method depends on node `design.method`. Read every data file and summary under each dependency readable directory. Compute the statistics needed to answer each research question (aggregate metrics, comparisons across conditions and baselines, significance where applicable), and describe the tables and figures that best present them (in enough detail that a later drafting step could describe them in prose without seeing the raw data again). Write the result as `analysis.md` (findings organized by research question, referencing the ablation results where they bear on a question) and `log.md` in the current directory.'

# --- drafting: chapter-by-chapter generation ---------------------------
python -m fatass modify build@drafting.outline --prompt 'Define build(gap: Gap, questions: Questions, method: Method, analysis: Analysis), where gap depends on node `review.gap`, questions depends on node `design.questions`, method depends on node `design.method`, and analysis depends on node `experiments.analysis`. Read every file under each dependency readable directory. Plan the full thesis chapter and section structure (Introduction, Related Work, Methodology, Results, Discussion, Conclusion, plus any subsections warranted), and within each section, one entry per planned paragraph: a self-contained prompt stating what that paragraph must argue, its role relative to its neighbors, and the specific claims, quotes, numbers, or figures it should draw on (naming exactly which upstream file each comes from). Write the result as `outline.md` (organized by chapter, then section, then paragraph entry) and `log.md` in the current directory.'

python -m fatass modify build@drafting.chapters.introduction --prompt 'Define build(outline: Outline, gap: Gap, style: Style), where outline depends on node `drafting.outline`, gap depends on node `review.gap` (for the motivation and novelty claim), and style depends on node `style` (its sub nodes `voice/register`, `voice/convention`, and `ai_pattern` together define the required academic register, formatting/citation conventions, and AI-writing patterns to avoid). Read every file under each dependency readable directory. Using only the Introduction paragraph entries in outline.md, write the Introduction chapter as continuous prose, one paragraph per entry, following the style conventions. Write the result as `draft.md` and `log.md` in the current directory.'

python -m fatass modify build@drafting.chapters.related_work --prompt 'Define build(outline: Outline, synthesis: Synthesis, related_work_plan: RelatedWorkPlan, style: Style), where outline depends on node `drafting.outline`, synthesis depends on node `review.synthesis`, related_work_plan depends on node `review.related_work_plan`, and style depends on node `style`. Read every file under each dependency readable directory. Using only the Related Work paragraph entries in outline.md, and following related_work_plan.md section order, write the Related Work chapter as continuous prose, following the style conventions. Write the result as `draft.md` and `log.md` in the current directory.'

python -m fatass modify build@drafting.chapters.methodology --prompt 'Define build(outline: Outline, protocol: Protocol, style: Style), where outline depends on node `drafting.outline`, protocol depends on node `design.protocol`, and style depends on node `style`. Read every file under each dependency readable directory. Using only the Methodology paragraph entries in outline.md, write the Methodology chapter as continuous prose, precise enough that a reader could reproduce the experiment from it, following the style conventions. Write the result as `draft.md` and `log.md` in the current directory.'

python -m fatass modify build@drafting.chapters.results --prompt 'Define build(outline: Outline, analysis: Analysis, style: Style), where outline depends on node `drafting.outline`, analysis depends on node `experiments.analysis`, and style depends on node `style`. Read every file under each dependency readable directory. Using only the Results paragraph entries in outline.md, write the Results chapter as continuous prose, reporting the findings and the tables/figures described in analysis.md without interpreting them, following the style conventions. Write the result as `draft.md` and `log.md` in the current directory.'

python -m fatass modify build@drafting.chapters.discussion --prompt 'Define build(outline: Outline, analysis: Analysis, gap: Gap, style: Style), where outline depends on node `drafting.outline`, analysis depends on node `experiments.analysis`, gap depends on node `review.gap`, and style depends on node `style`. Read every file under each dependency readable directory. Using only the Discussion paragraph entries in outline.md, write the Discussion chapter as continuous prose, interpreting the results against the research gap and questions and stating limitations honestly, following the style conventions. Write the result as `draft.md` and `log.md` in the current directory.'

python -m fatass modify build@drafting.chapters.conclusion --prompt 'Define build(outline: Outline, discussion: Discussion, style: Style), where outline depends on node `drafting.outline`, discussion depends on node `drafting.chapters.discussion` (its draft.md), and style depends on node `style`. Read every file under each dependency readable directory. Using only the Conclusion paragraph entries in outline.md, write the Conclusion chapter as continuous prose that follows naturally from the Discussion draft, following the style conventions. Write the result as `draft.md` and `log.md` in the current directory.'

python -m fatass modify build@drafting.assembly --prompt 'Define build(introduction: Introduction, related_work: RelatedWork, methodology: Methodology, results: Results, discussion: Discussion, conclusion: Conclusion), each depending respectively on nodes `drafting.chapters.introduction`, `drafting.chapters.related_work`, `drafting.chapters.methodology`, `drafting.chapters.results`, `drafting.chapters.discussion`, and `drafting.chapters.conclusion` (each dependency readable directory holds that chapter draft.md). Read every draft.md across all six dependencies. Concatenate them in thesis order under a heading per chapter, write a one-paragraph abstract summarizing the whole thesis, and a stub table of contents listing chapter and section titles. Write the result as `thesis.md` (abstract, table of contents, then the six chapters in order) and `log.md` in the current directory.'

python -m fatass modify build@drafting.annotation --prompt 'Define build(assembly: Assembly, ai_pattern: AiPattern), where assembly depends on node `drafting.assembly` (thesis.md) and ai_pattern depends on node `style.ai_pattern` (patterns typical of AI-generated writing, both micro and macro level). Read every file under each dependency readable directory. Go through thesis.md in order and flag every unit (line, sentence, sentence pair, or larger group) that shows a micro or macro AI pattern, quoting it verbatim and naming which pattern it matches. Write the result as `annotation.md` and `log.md` in the current directory.'

# --- audit: AI-pattern cleanup, cross-chapter consistency, human review -----
python -m fatass modify build@audit.draft --prompt 'Define build(draft: Assembly, annotation: Annotation), where draft depends on node `drafting.assembly` (thesis.md) and annotation depends on node `drafting.annotation` (annotation.md). Read every file under each dependency readable directory. Rewrite the flagged units to remove the noted AI patterns while preserving each unit original meaning, claims, and evidence exactly; leave every unflagged part unchanged. Write the result as `draft.md` (the full thesis with the flagged units revised) and `log.md` in the current directory.'

python -m fatass modify build@audit.consistency --prompt 'Define build(draft: Draft, protocol: Protocol, analysis: Analysis), where draft depends on node `audit.draft`, protocol depends on node `design.protocol`, and analysis depends on node `experiments.analysis`. Read every file under each dependency readable directory. Check the full thesis draft for cross-chapter consistency: terminology and notation used the same way everywhere, every claim in the Discussion traceable to a result actually reported in the Results chapter, every number or figure referenced matching protocol.md and analysis.md, and no orphaned forward/back references. Write every inconsistency found as `issues_auto.md`, one entry per issue naming the chapters and exact text involved, and `log.md` in the current directory.'

python -m fatass modify build@audit.draft_star --prompt 'Define build(draft: Draft, consistency: Consistency, issues: Issues), where draft depends on node `audit.draft`, consistency depends on node `audit.consistency` (issues_auto.md), and issues depends on node `audit.issues` (the advisor/human review notes). Read every file under each dependency readable directory. Resolve every issue, automated and human, by revising the draft accordingly, preserving the draft original meaning, claims, and evidence wherever an issue does not require changing them. Write the result as `draft.md` (the full thesis, final) and `log.md` in the current directory.'

# --- defense: thesis-specific final stage ------------------------------
python -m fatass modify build@defense.slides --prompt 'Define build(thesis: DraftStar), where thesis depends on node `audit.draft_star` (the final draft.md). Read every file under the dependency readable directory. Write a defense presentation outline as `slides.md`: one entry per slide, each with a title and the bullet points or figure to show, covering motivation, research questions, method, results, and conclusions in proportion to their weight in the thesis. Also write `log.md`.'

python -m fatass modify build@defense.qa_prep --prompt 'Define build(thesis: DraftStar, gap: Gap, analysis: Analysis), where thesis depends on node `audit.draft_star`, gap depends on node `review.gap`, and analysis depends on node `experiments.analysis`. Read every file under each dependency readable directory. Anticipate the questions a thesis committee is likely to ask, prioritizing the weakest points of the novelty claim and the limitations of the experiment, and write a prepared answer for each grounded in specific text or results from the dependencies. Write the result as `qa_prep.md` and `log.md` in the current directory.'
