import fatass
from fatass.topology.examples.phd_application.outreach.emails import Node as Emails
from fatass.topology.examples.phd_application.outreach.review import Node as Review


def build(emails: Emails, review: Review):
    fatass.free(
        readable=[emails, review],
        prompt=(
            f"Read `emails/index.json` in the readable directory for this "
            f"node's `emails` dependency — one entry per drafted outreach "
            f"email, each with a slug, recipient, institution, and which "
            f"document kinds from `profile.documents` (`cv`, "
            f"`transcripts`, `publications`, `writing_sample`, "
            f"`references`) should be attached — and every "
            f"`emails/<slug>.md` file alongside it, each containing the "
            f"recipient, subject line, and body for that slug.\n\n"
            f"Read `approved.json` in the readable directory for this "
            f"node's `review` dependency — a manual gate the applicant "
            f"populates by hand, listing the slugs (from "
            f"`emails/index.json`) that are cleared to send. If "
            f"`approved.json` is missing, empty, or lists no slugs, treat "
            f"that as nothing approved yet — not an error — and produce "
            f"empty/skip-everything outputs below rather than failing.\n\n"
            f"If `send_config.example.json` does not already exist in the "
            f"current directory, write one containing placeholder SMTP or "
            f"Gmail-API settings (e.g. host, port, username, password/"
            f"token fields — clearly fake placeholder values, never real "
            f"credentials), a placeholder sender name and email address, "
            f"and a `delay_seconds_between_sends` rate-limit setting. If "
            f"it already exists, leave it untouched.\n\n"
            f"Write `send_queue.json` in the current directory: an array "
            f"with one entry per slug that appears in `approved.json` and "
            f"also in `emails/index.json` — slugs absent from "
            f"`approved.json` must not appear here at all. Each entry "
            f"gives the recipient, subject, the path to that slug's body "
            f"file (`emails/<slug>.md`), the list of document kinds to "
            f"attach (from that slug's entry in `emails/index.json`), and "
            f"a `sent: false` flag.\n\n"
            f"Write `send.py` in the current directory: a standalone "
            f"script using only the standard library (`smtplib`, "
            f"`email`, etc.) that reads real settings from a sibling "
            f"`send_config.json` (never `send_config.example.json`) and "
            f"iterates `send_queue.json`, sending each entry whose `sent` "
            f"flag is still false. It must:\n"
            f"- Default to a `--dry-run` mode that only prints what each "
            f"send would do, without contacting any mail server.\n"
            f"- Require both an explicit `--live` command-line flag and a "
            f"typed `SEND` confirmation at a prompt before actually "
            f"sending anything.\n"
            f"- Honor `delay_seconds_between_sends` from `send_config.json` "
            f"between each send.\n"
            f"- As each entry is actually sent, mark it `sent: true` with "
            f"a timestamp and persist that back to `send_queue.json` "
            f"immediately, so a rerun never re-sends an entry already "
            f"marked sent.\n\n"
            f"Finally, write `log.md` in the current directory stating "
            f"how many emails were approved, how many were queued (should "
            f"match approved, unless an approved slug had no matching "
            f"`emails/index.json` entry), and how many were skipped and "
            f"why (e.g. present in `emails/index.json` but not approved)."
        ),
    )
