import fatass
from fatass.topology.cv.draft import Draft as Draft
from fatass.topology.cv.materials import Materials as Materials
from fatass.topology.cv.preferences import Preferences as Preferences


def build(draft: Draft, materials: Materials, preferences: Preferences):
    fatass.free(
        silent=True,
        model="opus",
        tools="Read,Write,Edit,Glob,Grep,Bash",  # Bash: the materials subdirectories hold PDFs, else Read misreads them as password-protected
        readable=[draft, materials, preferences],
        prompt=(
            f"Read `cv.md` in the readable directory for this node's "
            f"`draft` dependency: the assembled academic CV. If it isn't "
            f"there, the CV hasn't been assembled yet — do nothing and "
            f"write nothing.\n\n"
            f"Read `preferences.json` in the readable directory for this "
            f"node's `preferences` dependency: the candidate's answers to "
            f"the CV-writing questionnaire — which sections they want and "
            f"in what order, the citation style for publications, whether "
            f"to bold their own name in co-authored entries, whether to "
            f"split publications by subtype, and the CV's field, purpose, "
            f"and intended scope.\n\n"
            f"Also read every file under every subdirectory of the readable "
            f"directory for this node's `materials` dependency, including "
            f"its sub nodes: `education/`, `positions/`, "
            f"`publications_and_presentations/`, `funding_and_honors/`, "
            f"`teaching_and_service/`, `personal_projects/`, and "
            f"`references/`. Each holds the raw facts for its own category, "
            f"and is the only authority for them. Any of them may be empty. "
            f"A subdirectory may contain PDFs, and may hold a "
            f"`from_current_cv.md` written by that subnode's own extraction "
            f"transform alongside anything the candidate added by hand — "
            f"read all of it, both sources count equally. Three of these "
            f"bundle two distinct fact categories under their own \"## \" "
            f"subheadings: `publications_and_presentations/` (publications; "
            f"presentations and invited talks), `funding_and_honors/` "
            f"(grants and funding; awards and honors), and "
            f"`teaching_and_service/` (teaching; service).\n\n"
            f"Fact-check `cv.md` line by line against `materials`. For every "
            f"degree, position, publication, grant, award, teaching role, "
            f"service role, presentation, personal project, and referee "
            f"entry, find the specific file under `materials` that backs "
            f"it. Flag and fix:\n\n"
            f"- Any entry with no such backing file — it was invented, and "
            f"must be removed.\n"
            f"- Any date, title, venue, institution, affiliation, funding "
            f"amount, or co-author list that doesn't match its source file "
            f"exactly — correct it to what the source states. Where the "
            f"source states nothing, the detail doesn't belong in the CV at "
            f"all.\n\n"
            f"Then check formatting and internal consistency:\n\n"
            f"- The citation style preferences.json requests is applied "
            f"uniformly across every publication entry — no entry in a "
            f"different style from its neighbors.\n"
            f"- Sections appear in exactly the order preferences.json "
            f"requests.\n"
            f"- Entries within each section run reverse-chronologically, "
            f"most recent first, except where the section is inherently "
            f"unordered (References, for instance).\n"
            f"- If preferences.json asks for the candidate's own name to be "
            f"bolded, it is bolded in every co-authored entry, and nowhere "
            f"inconsistently.\n\n"
            f"If preferences.json requests a condensed or page-limited CV, "
            f"bring it within that limit by tightening wording and trimming "
            f"the least-relevant entries — judged against the stated target "
            f"field and the CV's stated purpose — rather than dropping "
            f"whole sections. A requested section stays in the CV even when "
            f"trimming leaves it short.\n\n"
            f"Edit `cv.md` in place, in the `draft` dependency's readable "
            f"directory, to fix everything you find. Preserve accurate "
            f"content exactly as written — change only what is actually "
            f"wrong, unsupported, or inconsistent. Do not rewrite the CV "
            f"wholesale, and do not touch any other file there.\n\n"
            f"Then write `audit_log.md` in the current directory, one "
            f"section per CV section, recording every fact-check and "
            f"formatting issue you found and how you fixed it — naming the "
            f"entry, what was wrong, the materials file you checked it "
            f"against, and the correction made. For a section where "
            f"everything checked out, record \"no issues found\"."
        ),
    )
